version: '3'

networks:
  dmz:
  backend:
  logging:

services:

  fluent:
    image: fluent/fluent-bit
    ports:
      - 127.0.0.1:24224:24224
    networks:
      - logging

  edge:
    image: traefik
    command: 
      - --api
      - --docker
      - --docker.swarmMode
      - --docker.watch
      - --accessLog
      - --accesslog.fields.defaultmode=keep
      - --accessLog.format=json
      - --traefikLog
      - --traefikLog.format=json
      - --web
      - --web.metrics.prometheus
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dmz
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: edge
        fluentd-async-connect:
        mode: non-blocking
        max-buffer-size: 4m

  web1:
    image: mattjtodd/go-http-canary
    build: ./services
    command: "-word=web1"
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.Hostname}}"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: web1
        fluentd-async-connect:
        mode: non-blocking
        max-buffer-size: 4m
    deploy:
      replicas: 0
      labels:
        - "traefik.backend=web"
        - "traefik.weight=1"
        - "traefik.port=3000"
        - "traefik.docker.network=backend"
        - "traefik.frontend.rule=PathPrefixStrip: /web/"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.healthcheck.path=/health"

  badCanary:
    image: mattjtodd/go-http-canary
    build: ./services
    command: "-word=badCanary -badCanary=true"
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.Hostname}}"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: web2
        fluentd-async-connect:
        mode: non-blocking
        max-buffer-size: 4m
    deploy:
      replicas: 0
      labels:
        - "traefik.backend=web"
        - "traefik.weight=1"
        - "traefik.port=3000"
        - "traefik.docker.network=backend"
        - "traefik.frontend.rule=PathPrefixStrip: /web/"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.healthcheck.path=/health"

  goodCanary:
    image: mattjtodd/go-http-canary
    build: ./services
    command: "-word=goodCanary -badCanary=false"
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.Hostname}}"
    networks:
      - backend
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: web2
        fluentd-async-connect:
        mode: non-blocking
        max-buffer-size: 4m
    deploy:
      replicas: 0
      labels:
        - "traefik.backend=web"
        - "traefik.weight=1"
        - "traefik.port=3000"
        - "traefik.docker.network=backend"
        - "traefik.frontend.rule=PathPrefixStrip: /web/"
        - "traefik.backend.loadbalancer.stickiness=true"
        - "traefik.backend.healthcheck.path=/health"
