[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/uber/jaeger-client-go"
  version = "2.14.0"

[prune]
  go-tests = true
  unused-packages = true
